version: '3'
services:
  dev:
    build:
      context: .
      args:
        - USERNAME=yang
        - USER_UID=1024
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    volumes:
      - /home/yang/workspace/harmless:/home/yang/workspace
      - /home/yang/data:/data
    # ports:
    #   - 7861:7860 # port forward for gradio
    command: /bin/sh -c "while sleep 1000; do :; done"